steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
           'pull',
           'gcr.io/$PROJECT_ID/seldon-core-python-example/build:latest',
        ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
           'build',
           '--cache-from=gcr.io/$PROJECT_ID/seldon-core-python-example/build:latest',
           '--tag=gcr.io/$PROJECT_ID/seldon-core-python-example/build:latest',
           '--tag=gcr.io/$PROJECT_ID/seldon-core-python-example/build:$COMMIT_SHA',
           './build',
        ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
           'pull',
           'gcr.io/$PROJECT_ID/seldon-core-python-example/model:latest',
        ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
           'build',
           ## `--cache-from` only works in the last stage of the build, see https://github.com/moby/moby/issues/34715
           '--cache-from=gcr.io/$PROJECT_ID/seldon-core-python-example/model:latest',
           '--tag=gcr.io/$PROJECT_ID/seldon-core-python-example/model:latest',
           '--tag=gcr.io/$PROJECT_ID/seldon-core-python-example/model:$COMMIT_SHA',
           '--build-arg=BUILD_IMAGE=gcr.io/$PROJECT_ID/seldon-core-python-example/build:$COMMIT_SHA',
           '--build-arg=IMAGE_REPO=gcr.io/$PROJECT_ID/seldon-core-python-example/model',
           '--build-arg=IMAGE_VERSION=$COMMIT_SHA',
           '--build-arg=MODEL_NAME=IrisClassifier',
           './model',
        ]
images:
- 'gcr.io/$PROJECT_ID/seldon-core-python-example/build:latest'
- 'gcr.io/$PROJECT_ID/seldon-core-python-example/build:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/seldon-core-python-example/model:latest'
- 'gcr.io/$PROJECT_ID/seldon-core-python-example/model:$COMMIT_SHA'
timeout: '40m'
