steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
           'pull',
           'gcr.io/$PROJECT_ID/$REPO_NAME:latest'
        ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
           'build',
           '--cache-from=gcr.io/$PROJECT_ID/$REPO_NAME:latest',
           '--tag=gcr.io/$PROJECT_ID/$REPO_NAME:latest',
           '--tag=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',
           '--build-arg=IMAGE_REPO=gcr.io/$PROJECT_ID/$REPO_NAME',
           '--build-arg=IMAGE_VERSION=$COMMIT_SHA',
           '--build-arg=MODEL_NAME=IrisClassifier',
           '.'
        ]
images:
- 'gcr.io/$PROJECT_ID/$REPO_NAME:latest'
- 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
# Re-building Python dependencies can take about 30min, but for some reason
# giving the builder 8 cores with options: {machineType: 'N1_HIGHCPU_8'}
# only wins a few minutes
timeout: '40m'
