kind: Service
apiVersion: v1
metadata:
  name: mysql
  labels:
    name: mysql
    service: seldon
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    name: mysql
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
