#!/bin/bash -eux

do_setup() {
  scripts/seldon-cli client --action zk_push
  scripts/seldon-cli memcached --action setup --servers memcached1:11211,memcached2:11211
  scripts/seldon-cli memcached --action commit
  kubectl exec -ti "$(kubectl get pod -l name=zookeeper1 -o jsonpath='{.items..metadata.name}')" -- /opt/zookeeper/bin/zkCli.sh delete /config/dbcp
  scripts/seldon-cli db --action setup --db-name ClientDB --db-user root --db-password mypass --db-jdbc 'jdbc:mysql:replication://mysql:3306,mysql:3306/?characterEncoding=utf8&useServerPrepStmts=true&logger=com.mysql.jdbc.log.StandardLogger&roundRobinLoadBalance=true&transformedBitIsBoolean=true&rewriteBatchedStatements=true'
  scripts/seldon-cli db --action commit
  scripts/seldon-cli client --action setup --db-name ClientDB --client-name test
}

get_seldon_server_pod() {
  kubectl get pod -l name=seldon-server "$@"
}


seldod_server_pod_ready() {
  get_seldon_server_pod -o jsonpath='{range .items[*]}{range @.status.conditions[*]}{@.type}={@.status};{end}{end}' \
    | grep -q 'Initialized=True;Ready=True;PodScheduled=True;'
}

#kubectl delete pods -l name=seldon-server
#sleep 10
until seldod_server_pod_ready ; do sleep 1 ; done
do_setup
