#!/bin/bash -eux

json_src=(
  "${SELDON_SERVER:-"./seldon-server"}/kubernetes/conf/hostpath.json"
  "${SELDON_SERVER:-"./seldon-server"}/kubernetes/conf/mysql.json"
  "${SELDON_SERVER:-"./seldon-server"}/kubernetes/conf/memcache.json"
  "${SELDON_SERVER:-"./seldon-server"}/kubernetes/conf/redis.json"
  "${SELDON_SERVER:-"./seldon-server"}/kubernetes/conf/zookeeper.json"
  "${SELDON_SERVER:-"./seldon-server"}/kubernetes/conf/control.json"
  "${SELDON_SERVER:-"./seldon-server"}/kubernetes/conf/influxdb-grafana.json"
  "${SELDON_SERVER:-"./seldon-server"}/kubernetes/conf/kafka.json"
  "${SELDON_SERVER:-"./seldon-server"}/kubernetes/conf/td-agent-server.json"
  "${SELDON_SERVER:-"./seldon-server"}/kubernetes/conf/spark-master.json"
  "${SELDON_SERVER:-"./seldon-server"}/kubernetes/conf/spark-workers.json"
  "${SELDON_SERVER:-"./seldon-server"}/kubernetes/conf/spark-ui.json"
  "${SELDON_SERVER:-"./seldon-server"}/kubernetes/conf/server.json"
  "${SELDON_SERVER:-"./seldon-server"}/kubernetes/conf/analytics/impressions-kafka-stream.json"
  "${SELDON_SERVER:-"./seldon-server"}/kubernetes/conf/analytics/predictions-kafka-stream.json"
)

./scripts/import-json-as-yaml infra "${json_src[@]}"
