#!/bin/bash -eux

dest_dir="${1}"
shift
json_src=("$@")

mkdir -p "${dest_dir}"
touch output.json

for file in "${json_src[@]}" ; do
  for data in "$(jq -c 'select(.kind != "List")' $file)" ; do
     [ -n "${data}" ] && echo "${data}" >> output.json
  done
  for data in "$(jq -c 'select(.kind == "List") | .items[]' $file)" ; do
     [ -n "${data}" ] && echo "${data}" >> output.json
  done
done

for name in $(jq -c '[.metadata.name,.kind]' < output.json) ; do
  file="${dest_dir}/$(jq -r -n --argjson name "${name}" '$name | join(".")').yaml"
  jq --argjson name "${name}" 'select(.metadata.name == $name[0]) | select(.kind == $name[1])' < output.json | json2yaml > "${file}"
done

rm -f output.json
